# Generated by Django 2.0.7 on 2018-08-13 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('due_date', models.DateField()),
                ('created_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
